options {
    directory "/var/cache/bind";

    listen-on { any; };
    listen-on-v6 { none; };

    allow-query { any; };
    recursion yes;

    forwarders {
        8.8.8.8;
        1.1.1.1;
    };

    dnssec-validation no;
};

zone "examplenv.demo" IN {
    type master;
    file "/zones/db.examplenv.demo";
};

zone "10.10.10.in-addr.arpa" IN {
    type master;
    file "/zones/db.10.10.10.in-addr.arpa";
};

controls {
    inet 127.0.0.1 port 1953 allow { 127.0.0.1; } keys { "rndc-key"; };
};

zone "testzone.local" {
    type master;
    file "/zones/db.testzone.local";
    allow-update { none; };
};

zone "testzone2.local" {
    type master;
    file "/zones/db.testzone2.local";
    allow-update { none; };
};

zone "testzone3.local" {
    type master;
    file "/zones/db.testzone3.local";
    allow-update { none; };
};

zone "testzone4.local" {
    type master;
    file "/zones/db.testzone4.local";
    allow-update { none; };
};

zone "testzone5.local" {
    type master;
    file "/zones/db.testzone5.local";
    allow-update { none; };
};

include "/etc/bind/rndc.key";

